import type { Product, Category, Order, Review, ReturnRequest, User } from "./types"

export const categories: Category[] = [
  { id: "1", name: "Платья", slug: "dresses", image: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600&h=800&fit=crop" },
  { id: "2", name: "Блузки", slug: "blouses", image: "https://images.unsplash.com/photo-1564257631407-4deb1f99d992?w=600&h=800&fit=crop" },
  { id: "3", name: "Юбки", slug: "skirts", image: "https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=600&h=800&fit=crop" },
  { id: "4", name: "Брюки", slug: "pants", image: "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600&h=800&fit=crop" },
  { id: "5", name: "Верхняя одежда", slug: "outerwear", image: "https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=600&h=800&fit=crop" },
  { id: "6", name: "Аксессуары", slug: "accessories", image: "https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?w=600&h=800&fit=crop" },
]

export const products: Product[] = [
  {
    id: "1",
    name: "Шёлковое платье Aurelia",
    slug: "silk-dress-aurelia",
    description: "Элегантное шёлковое платье с V-образным вырезом и струящимся силуэтом. Идеально для вечерних мероприятий и особых случаев. Натуральный шёлк обеспечивает комфорт и роскошный вид.",
    price: 12900,
    oldPrice: 18900,
    discount: 32,
    images: [
      "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=600&h=800&fit=crop",
      "https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=600&h=800&fit=crop",
      "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600&h=800&fit=crop",
    ],
    category: "Платья",
    categorySlug: "dresses",
    brand: "MonDiva",
    colors: ["Чёрный", "Бежевый", "Бордовый"],
    sizes: ["XS", "S", "M", "L"],
    rating: 4.8,
    reviewCount: 24,
    isNew: true,
    isPopular: true,
    inStock: true,
    createdAt: "2025-12-01",
  },
  {
    id: "2",
    name: "Блузка Stella из органзы",
    slug: "organza-blouse-stella",
    description: "Воздушная блузка из органзы с объёмными рукавами. Идеальна как для офиса, так и для романтических свиданий.",
    price: 5900,
    images: [
      "https://images.unsplash.com/photo-1564257631407-4deb1f99d992?w=600&h=800&fit=crop",
      "https://images.unsplash.com/photo-1551163943-3f6a855d1153?w=600&h=800&fit=crop",
    ],
    category: "Блузки",
    categorySlug: "blouses",
    brand: "Elegance",
    colors: ["Белый", "Пудровый"],
    sizes: ["XS", "S", "M", "L", "XL"],
    rating: 4.5,
    reviewCount: 18,
    isNew: true,
    isPopular: false,
    inStock: true,
    createdAt: "2025-11-20",
  },
  {
    id: "3",
    name: "Юбка-миди плиссе Viva",
    slug: "pleated-midi-skirt-viva",
    description: "Плиссированная юбка-миди из сатина. Универсальная модель, которая сочетается с любым верхом.",
    price: 4500,
    oldPrice: 6200,
    discount: 27,
    images: [
      "https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=600&h=800&fit=crop",
      "https://images.unsplash.com/photo-1592301933927-35b597393c0a?w=600&h=800&fit=crop",
    ],
    category: "Юбки",
    categorySlug: "skirts",
    brand: "MonDiva",
    colors: ["Изумрудный", "Чёрный", "Бежевый"],
    sizes: ["S", "M", "L"],
    rating: 4.7,
    reviewCount: 31,
    isNew: false,
    isPopular: true,
    inStock: true,
    createdAt: "2025-10-15",
  },
  {
    id: "4",
    name: "Брюки-палаццо Roma",
    slug: "palazzo-pants-roma",
    description: "Широкие брюки-палаццо с высокой посадкой. Визуально удлиняют ноги и создают элегантный силуэт.",
    price: 7200,
    images: [
      "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=600&h=800&fit=crop",
      "https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=600&h=800&fit=crop",
    ],
    category: "Брюки",
    categorySlug: "pants",
    brand: "Urban Chic",
    colors: ["Чёрный", "Серый", "Молочный"],
    sizes: ["XS", "S", "M", "L", "XL"],
    rating: 4.6,
    reviewCount: 15,
    isNew: false,
    isPopular: true,
    inStock: true,
    createdAt: "2025-09-05",
  },
  {
    id: "5",
    name: "Тренч Classic Beige",
    slug: "trench-classic-beige",
    description: "Классический тренч из водоотталкивающей ткани. Вечная модель, которая никогда не выйдет из моды.",
    price: 15900,
    oldPrice: 21000,
    discount: 24,
    images: [
      "https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=600&h=800&fit=crop",
      "https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=600&h=800&fit=crop",
    ],
    category: "Верхняя одежда",
    categorySlug: "outerwear",
    brand: "MonDiva",
    colors: ["Бежевый", "Чёрный"],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.9,
    reviewCount: 42,
    isNew: false,
    isPopular: true,
    inStock: true,
    createdAt: "2025-08-10",
  },
  {
    id: "6",
    name: "Кожаная сумка Firenze",
    slug: "leather-bag-firenze",
    description: "Компактная сумка из натуральной кожи с золотой фурнитурой. Идеальный аксессуар на каждый день.",
    price: 9800,
    images: [
      "https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?w=600&h=800&fit=crop",
      "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=600&h=800&fit=crop",
    ],
    category: "Аксессуары",
    categorySlug: "accessories",
    brand: "Luxe",
    colors: ["Чёрный", "Коричневый", "Бежевый"],
    sizes: ["One Size"],
    rating: 4.4,
    reviewCount: 12,
    isNew: true,
    isPopular: false,
    inStock: true,
    createdAt: "2025-12-10",
  },
  {
    id: "7",
    name: "Кашемировый свитер Soft Touch",
    slug: "cashmere-sweater-soft-touch",
    description: "Мягкий кашемировый свитер оверсайз. Невероятно приятный к телу и уютный.",
    price: 11500,
    oldPrice: 14500,
    discount: 21,
    images: [
      "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=600&h=800&fit=crop",
      "https://images.unsplash.com/photo-1434389677669-e08b4cda3a5d?w=600&h=800&fit=crop",
    ],
    category: "Блузки",
    categorySlug: "blouses",
    brand: "MonDiva",
    colors: ["Пудровый", "Серый", "Молочный"],
    sizes: ["S", "M", "L"],
    rating: 4.9,
    reviewCount: 56,
    isNew: false,
    isPopular: true,
    inStock: true,
    createdAt: "2025-07-20",
  },
  {
    id: "8",
    name: "Вечернее платье Noir",
    slug: "evening-dress-noir",
    description: "Роскошное чёрное платье в пол с открытой спиной. Создано для самых важных событий.",
    price: 22900,
    images: [
      "https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=600&h=800&fit=crop",
      "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=600&h=800&fit=crop",
    ],
    category: "Платья",
    categorySlug: "dresses",
    brand: "Luxe",
    colors: ["Чёрный"],
    sizes: ["XS", "S", "M", "L"],
    rating: 5.0,
    reviewCount: 8,
    isNew: true,
    isPopular: false,
    inStock: true,
    createdAt: "2025-12-15",
  },
  {
    id: "9",
    name: "Льняные брюки Riviera",
    slug: "linen-pants-riviera",
    description: "Лёгкие льняные брюки свободного кроя. Идеальны для жаркого лета и путешествий.",
    price: 4900,
    images: [
      "https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=600&h=800&fit=crop",
    ],
    category: "Брюки",
    categorySlug: "pants",
    brand: "Elegance",
    colors: ["Белый", "Бежевый", "Голубой"],
    sizes: ["XS", "S", "M", "L", "XL"],
    rating: 4.3,
    reviewCount: 19,
    isNew: false,
    isPopular: false,
    inStock: true,
    createdAt: "2025-06-01",
  },
  {
    id: "10",
    name: "Шарф из кашемира Aura",
    slug: "cashmere-scarf-aura",
    description: "Большой шарф из 100% кашемира. Невесомый, тёплый и невероятно мягкий.",
    price: 6500,
    oldPrice: 8500,
    discount: 24,
    images: [
      "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=600&h=800&fit=crop",
    ],
    category: "Аксессуары",
    categorySlug: "accessories",
    brand: "MonDiva",
    colors: ["Серый", "Бежевый", "Бордовый"],
    sizes: ["One Size"],
    rating: 4.7,
    reviewCount: 22,
    isNew: false,
    isPopular: true,
    inStock: true,
    createdAt: "2025-09-20",
  },
  {
    id: "11",
    name: "Пальто-халат Milano",
    slug: "robe-coat-milano",
    description: "Стильное пальто-халат с поясом. Универсальный вариант на осень и весну.",
    price: 18500,
    images: [
      "https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=600&h=800&fit=crop",
    ],
    category: "Верхняя одежда",
    categorySlug: "outerwear",
    brand: "Urban Chic",
    colors: ["Кэмел", "Серый"],
    sizes: ["S", "M", "L"],
    rating: 4.6,
    reviewCount: 14,
    isNew: true,
    isPopular: false,
    inStock: true,
    createdAt: "2025-11-01",
  },
  {
    id: "12",
    name: "Атласная юбка Glow",
    slug: "satin-skirt-glow",
    description: "Атласная юбка с лёгким блеском. Создаёт изысканный вечерний образ.",
    price: 5400,
    images: [
      "https://images.unsplash.com/photo-1592301933927-35b597393c0a?w=600&h=800&fit=crop",
    ],
    category: "Юбки",
    categorySlug: "skirts",
    brand: "Elegance",
    colors: ["Шампань", "Чёрный", "Изумрудный"],
    sizes: ["XS", "S", "M", "L"],
    rating: 4.5,
    reviewCount: 9,
    isNew: false,
    isPopular: false,
    inStock: true,
    createdAt: "2025-10-05",
  },
]

export const reviews: Review[] = [
  { id: "1", userId: "1", userName: "Анна К.", productId: "1", rating: 5, text: "Потрясающее платье! Ткань очень приятная, села идеально по фигуре.", isApproved: true, createdAt: "2025-12-05" },
  { id: "2", userId: "2", userName: "Мария С.", productId: "1", rating: 4, text: "Красивое, но размер чуть больше, чем ожидала. Взяла S, а надо было XS.", isApproved: true, createdAt: "2025-12-10" },
  { id: "3", userId: "3", userName: "Елена В.", productId: "5", rating: 5, text: "Лучший тренч, который у меня был! Качество на высшем уровне.", isApproved: true, createdAt: "2025-11-20" },
  { id: "4", userId: "4", userName: "Ольга Н.", productId: "7", rating: 5, text: "Обожаю этот свитер, невероятно мягкий и тёплый. Ношу каждый день!", isApproved: true, createdAt: "2025-11-15" },
  { id: "5", userId: "5", userName: "Дарья П.", productId: "3", rating: 4, text: "Красивая юбка, хорошо сочетается с разными топами.", isApproved: false, createdAt: "2025-12-12" },
  { id: "6", userId: "1", userName: "Анна К.", productId: "8", rating: 5, text: "Шикарное вечернее платье, все в восторге!", isApproved: true, createdAt: "2025-12-18" },
]

export const orders: Order[] = [
  {
    id: "ORD-001",
    userId: "1",
    items: [
      { productId: "1", name: "Шёлковое платье Aurelia", image: products[0].images[0], size: "S", color: "Чёрный", quantity: 1, price: 12900 },
      { productId: "6", name: "Кожаная сумка Firenze", image: products[5].images[0], size: "One Size", color: "Чёрный", quantity: 1, price: 9800 },
    ],
    total: 22700,
    status: "delivered",
    address: "Москва, ул. Тверская 15, кв. 42",
    deliveryMethod: "Курьерская доставка",
    paymentMethod: "Банковская карта",
    createdAt: "2025-11-15",
    updatedAt: "2025-11-20",
  },
  {
    id: "ORD-002",
    userId: "1",
    items: [
      { productId: "7", name: "Кашемировый свитер Soft Touch", image: products[6].images[0], size: "M", color: "Пудровый", quantity: 1, price: 11500 },
    ],
    total: 11500,
    status: "shipped",
    address: "Москва, ул. Тверская 15, кв. 42",
    deliveryMethod: "СДЭК",
    paymentMethod: "Банковская карта",
    createdAt: "2025-12-10",
    updatedAt: "2025-12-12",
  },
  {
    id: "ORD-003",
    userId: "2",
    items: [
      { productId: "5", name: "Тренч Classic Beige", image: products[4].images[0], size: "M", color: "Бежевый", quantity: 1, price: 15900 },
    ],
    total: 15900,
    status: "processing",
    address: "Санкт-Петербург, Невский пр. 88, кв. 12",
    deliveryMethod: "Почта России",
    paymentMethod: "При получении",
    createdAt: "2025-12-18",
    updatedAt: "2025-12-18",
  },
]

export const returnRequests: ReturnRequest[] = [
  { id: "RET-001", orderId: "ORD-001", userId: "1", reason: "Не подошёл размер", status: "approved", createdAt: "2025-11-22" },
  { id: "RET-002", orderId: "ORD-003", userId: "2", reason: "Не соответствует описанию", status: "pending", createdAt: "2025-12-20" },
]

export const users: User[] = [
  { id: "1", email: "anna@example.com", name: "Анна Крылова", phone: "+7 (999) 123-45-67", role: "user", createdAt: "2025-01-15" },
  { id: "2", email: "maria@example.com", name: "Мария Смирнова", phone: "+7 (999) 234-56-78", role: "user", createdAt: "2025-03-20" },
  { id: "3", email: "elena@example.com", name: "Елена Волкова", role: "moderator", createdAt: "2025-02-10" },
  { id: "4", email: "admin@mondiva.com", name: "Администратор", role: "admin", createdAt: "2025-01-01" },
  { id: "5", email: "logistics@mondiva.com", name: "Логист Иванов", role: "logistics", createdAt: "2025-01-01" },
]
